### ISSUE TITLE
Assignment 2 Help - Not a Submission

### ISSUE THREAD

**Issue by marygeschwindt** [VIS-2129-F2020/mgeschwindt-vis#2]
Hello -

I'm running into an issue in my code for one of my figures that I have been struggling to find a solution for. For my second figure of the non-continuous cartogram, the scale of the figure comes out very tiny. I can't seem to figure out a way to scale the entire figure so that it's larger. There seems to be no other issue with scale in my other maps/figures. Also, I'm not quite sure how to break up the numbers in the legend so that they're not overlapping.

Link here: https://vis-2129-f2020.github.io/mgeschwindt-vis/Assignment_2_Maps 

Thank you in advance for your help!

@c-voulgaris 
@bauranov 
@traemalcolm

**Comment by bauranov** [comment]
Hi,

The numbers in the legend are overlapping because the breaks and labels range from 100k to 1M. The population of European countries is up to 100M, Russia is about 150M, I think. I would suggest changing the range from 0 to 150M by 30M increments. See if that works well, if not, try some other range:
breaks = seq(0, 150000000, by = 30000000),
                       labels = formatC(seq(0, 150000000, by = 30000000),

The scale is small because R is trying to fit all the countries into the plot. There are overseas territories in the projection you selected which is stretching the map. You can either manually select the countries you want to present, without the overseas territories, or select projection eu_coord3. 

Hope that helps!

**Comment by marygeschwindt** [comment]
Hi Alex,

Thank you for your help! Those numbers were a better selection and worked with the numbers in the legend.

As for the scale of the cartogram, I am unable to use the projection eu_coord3, as I get an error that says it needs to be transformed. Even when I transform this projection, I get the same error. But, I will try to manually select the countries instead and see if that helps. Either way, I've learned something new. Thank you!
