### ISSUE TITLE
Assignment 3 Error - Not a Submission

### ISSUE THREAD

**Issue by marygeschwindt** [VIS-2129-F2020/mgeschwindt-vis#4]
Hi Carole,

I've committed my Assignment 3 files to Git for you to take a look at the error in my code. The error shows up in Calculation #6, at the very end of my file. Please note that in order to get the file to "knit", I used "#" to cancel out the code which was creating the error in this section.

Link here: https://vis-2129-f2020.github.io/mgeschwindt-vis/Assignment3#Geospatial_Data

Thank you for taking a look!

@c-voulgaris

**Comment by c-voulgaris** [comment]
The error you're getting is because your bike_parking layer includes some points with empty geometries. In other words, there is a row for the point, but the geometry column is empty. You can fix this by adding and running the following lines before you do calculation 6:

```
bike_parking <- bike_parking %>%
  filter(!is.na(st_dimension(bike_parking)))
```

BUT, you'll find that you have a second error after that, which comes from using a coordinate system in units of "US_survey_feet", which st_nn can't seem to handle. Try using a different coordinate system instead. This one seems to work:

+proj=tmerc +lat_0=38.83333333333334 +lon_0=-74.5 +k=0.9999 +x_0=150000 +y_0=0 +ellps=GRS80 +units=m +no_defs 

Which I found here: https://spatialreference.org/ref/esri/102315/

So you'd replace line 54 with: 

```
NY_state_tmerc <- "+proj=tmerc +lat_0=38.83333333333334 +lon_0=-74.5 +k=0.9999 +x_0=150000 +y_0=0 +ellps=GRS80 +units=m +no_defs"
```

That should work for you
