### ISSUE TITLE
Issue Loading Libraries

### ISSUE THREAD

**Issue by marygeschwindt** [VIS-2129-F2020/mgeschwindt-vis#9]
Hi Carole, Alex, and Taelor,

I attempted to set up my assignment 5 this evening and had an error loading my tidyverse and other libraries. I've gone on an extensive google search and have tried everything from uninstalling, reinstalling, and updating libraries, to deleting my local directory and creating a new project from scratch for my mgeschwindt-vis repo.

Do you have any additional thoughts on how to resolve this error? The specific error I'm getting is: 
**Error: package or namespace load failed for ‘tidyverse’**
I will also get similar errors for other libraries that I'm trying to load.

My assignment 5 has been committed and is located here: https://github.com/VIS-2129-F2020/mgeschwindt-vis/blob/master/Assignment-5-Interactive-Map.Rmd

Thank you for your help on this issue!

-Mary

**Comment by c-voulgaris** [comment]
It works on my computer, which isn't surprising since this is an error about what is or isn't installed on our computer. I believe you when you say you tried a ton of Googling and uninstalling/reinstalling already, so you've probably already come across this: [https://stackoverflow.com/questions/31717850/error-package-or-namespace-load-failed-for-ggplot2-and-for-data-table](https://stackoverflow.com/questions/31717850/error-package-or-namespace-load-failed-for-ggplot2-and-for-data-table){target="_blank"}

Please sign up for office hours so we can troubleshoot this together.

**Comment by marygeschwindt** [comment]
The problem was definitely an issue with OneDrive, which I have now been able to resolve!

The problem that all of the files within my documents folder had a path that included "OneDrive" even though I had uninstalled OneDrive on my computer. Getting to the root of the problem meant figuring out how to get rid of the OneDrive portion of the file path. I managed to do this by restoring the file path locations to be their default: opening my documents folder in windows explorer, then going to the Properties tab > Location tab > Restore Default and hitting "Ok".

I reopened R (no need to reinstall it), and I reinstalled every library (just to make sure they were now going to the correct file path). Then, I ran the libraries, and it worked perfectly.

It was quite a Google search to figure out how to do this, but I have learned a very valuable lesson here about ensuring I know exactly what's happening to my files prior to attempting a backup or cloud storage of everything on my computer.

Carole - thank you so much for putting in the time yesterday morning to help me troubleshoot!
